version: 0.0.1

services:
    elasticsearch:
        container_name: elastic
        image: elasticsearch:7.17.8
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=false
        ports:
            - "9200:9200"
        volumes:
            - ./docker/elastic_data:/usr/share/elasticsearch_data/data

    kibana:
        container_name: kibana
        image: kibana:7.17.8
        environment:
            ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
        ports:
            - "5601:5601"
        volumes:
            - ./docker/kibana_data:/usr/share/kibana_data/kibana
        depends_on:
            - elasticsearch

networks:
    elasticNetwork:
        driver: bridge

volumes:
    elk-data:
